export const REGISTER_USER="REGISTER_USER"
export const REGISTER_SUCESS="REGISTER_SUCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"

export const LOGIN_USER="LOGIN_USER"
export const LOGIN_SUCESS="LOGIN_SUCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const GET_PROFILE="GET_PROFILE"
export const GET_PROFILE_SUCESS="GET_PROFILE_SUCESS"
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE"

export const GET_PATIENT="GET_PATIENT"
export const GET_PATIENT_SUCESS="GET_PATIENT_SUCESS"
export const GET_PATIENT_FAILURE="GET_PATIENT_FAILURE"

export const REGISTER_PATIENT_PROFILE="REGISTER_PATIENT_PROFILE"
export const REGISTER_PATIENT_PROFILE_SUCESS="REGISTER_PATIENT_PROFILE_SUCESS"
export const REGISTER_PATIENT_PROFILE_FAILURE="REGISTER_PATIENT_PROFILE_FAILURE"

export const UPDATE_PATIENT_PROFILE="UPDATE_PATIENT_PROFILE"
export const UPDATE_PATIENT_PROFILE_SUCESS="UPDATE_PATIENT_PROFILE_SUCESS"
export const UPDATE_PATIENT_PROFILE_FAILURE="UPDATE_PATIENT_PROFILE_FAILURE"

export const PATIENT_INSERT_POST="PATIENT_INSERT_POST"
export const PATIENT_INSERT_POST_SUCESS="PATIENT_INSERT_POST_SUCESS"
export const PATIENT_INSERT_POST_FAILURE="PATIENT_INSERT_POST_FAILURE"

export const GET_PATIENT_POST="GET_PATIENT_POST"
export const GET_PATIENT_POST_SUCESS="GET_PATIENT_POST_SUCESS"
export const GET_PATIENT_POST_FAILURE="GET_PATIENT_POST_FAILURE"

export const UPDATE_PATIENT_POST="UPDATE_PATIENT_POST"
export const UPDATE_PATIENT_POST_SUCESS="UPDATE_PATIENT_POST_SUCESS"
export const UPDATE_PATIENT_POST_FAILURE="UPDATE_PATIENT_POST_FAILURE"
